version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@db/bus_booking_db
      - REDIS_URL=redis://redis:6379/0

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bus_booking_db

  redis:
    image: redis:6

volumes:
  postgres_data: